import { nanoid } from "@reduxjs/toolkit";
import React from "react";
import { TvShow, Video } from "../../types";
import Card from "../Card/Card";

export function TestCard() {
  const mockDataTvShow: TvShow = {
    _id: "620a595fdafc5bd29f9d8596",
    name: "game of thrones",
    location:
      "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game of Thrones S07 Complete Season 7 720p x264 AC3 5.1 (MP4)",
    seasons: [
      {
        number: "7",
        episodes: [
          {
            number: "3",
            ref: {
              _id: "620a595fdafc5bd29f9d8593",
              name: "game of thrones s07e03",
              basename: "game of thrones",
              filename:
                "Game.Of.Thrones.S07E03.The.Queens.Justice.720p.WEB-DL.Re-encode.mp4",
              ext: ".mp4",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game of Thrones S07 Complete Season 7 720p x264 AC3 5.1 (MP4)",
              type: "tv",
              episode: "3",
              season: "7",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.447Z",
              updatedAt: "2022-02-14T13:30:07.447Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d8598",
          },
          {
            number: "4",
            ref: {
              _id: "620a595fdafc5bd29f9d859d",
              name: "game of thrones s07e04",
              basename: "game of thrones",
              filename:
                "Game.Of.Thrones.S07E04.The.Spoils.Of.War.720p.WEB-DL.Re-encode.mp4",
              ext: ".mp4",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game of Thrones S07 Complete Season 7 720p x264 AC3 5.1 (MP4)",
              type: "tv",
              episode: "4",
              season: "7",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.474Z",
              updatedAt: "2022-02-14T13:30:07.474Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d85a2",
          },
          {
            number: "7",
            ref: {
              _id: "620a595fdafc5bd29f9d85a5",
              name: "game of thrones s07e07",
              basename: "game of thrones",
              filename:
                "Game.Of.Thrones.S07E07.The.Dragon.And.The.Wolf.720p.WEB-DL.Re-encode.mp4",
              ext: ".mp4",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game of Thrones S07 Complete Season 7 720p x264 AC3 5.1 (MP4)",
              type: "tv",
              episode: "7",
              season: "7",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.507Z",
              updatedAt: "2022-02-14T13:30:07.507Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d85ab",
          },
          {
            number: "6",
            ref: {
              _id: "620a595fdafc5bd29f9d85ae",
              name: "game of thrones s07e06",
              basename: "game of thrones",
              filename:
                "Game.Of.Thrones.S07E06.Beyond.The.Wall.720p.WEB-DL.Re-encode.mp4",
              ext: ".mp4",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game of Thrones S07 Complete Season 7 720p x264 AC3 5.1 (MP4)",
              type: "tv",
              episode: "6",
              season: "7",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.523Z",
              updatedAt: "2022-02-14T13:30:07.523Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d85b5",
          },
          {
            number: "2",
            ref: {
              _id: "620a595fdafc5bd29f9d85b8",
              name: "game of thrones s07e02",
              basename: "game of thrones",
              filename:
                "Game.Of.Thrones.S07E02.Stormborn.720p.WEB-DL.Re-encode.mp4",
              ext: ".mp4",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game of Thrones S07 Complete Season 7 720p x264 AC3 5.1 (MP4)",
              type: "tv",
              episode: "2",
              season: "7",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.535Z",
              updatedAt: "2022-02-14T13:30:07.535Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d85c0",
          },
          {
            number: "1",
            ref: {
              _id: "620a595fdafc5bd29f9d85c3",
              name: "game of thrones s07e01",
              basename: "game of thrones",
              filename:
                "Game.Of.Thrones.S07E01.Dragonstone.720p.WEB-DL.Re-encode.mp4",
              ext: ".mp4",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game of Thrones S07 Complete Season 7 720p x264 AC3 5.1 (MP4)",
              type: "tv",
              episode: "1",
              season: "7",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.549Z",
              updatedAt: "2022-02-14T13:30:07.549Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d85cc",
          },
          {
            number: "5",
            ref: {
              _id: "620a595fdafc5bd29f9d85cf",
              name: "game of thrones s07e05",
              basename: "game of thrones",
              filename:
                "Game.Of.Thrones.S07E05.Eastwatch.720p.WEB-DL.Re-encode.mp4",
              ext: ".mp4",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game of Thrones S07 Complete Season 7 720p x264 AC3 5.1 (MP4)",
              type: "tv",
              episode: "5",
              season: "7",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.565Z",
              updatedAt: "2022-02-14T13:30:07.565Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d85d9",
          },
        ],
        _id: "620a595fdafc5bd29f9d8597",
      },
      {
        number: "6",
        episodes: [
          {
            number: "7",
            ref: {
              _id: "620a595fdafc5bd29f9d85dc",
              name: "game of thrones s06e07",
              basename: "game of thrones",
              filename:
                "game.of.thrones.s06e07.the.broken.man.vostfr.720p.TVrip.Xvid.dRuIdE.avi",
              ext: ".avi",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 6",
              type: "tv",
              episode: "7",
              season: "6",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.581Z",
              updatedAt: "2022-02-14T13:30:07.581Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d85e8",
          },
          {
            number: "10",
            ref: {
              _id: "620a595fdafc5bd29f9d85eb",
              name: "game of thrones s06e10",
              basename: "game of thrones",
              filename:
                "game.of.thrones.s06e10.the.winds.of.winter.720p.TVrip.Xvid.dRuIdE.avi",
              ext: ".avi",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 6",
              type: "tv",
              episode: "10",
              season: "6",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.596Z",
              updatedAt: "2022-02-14T13:30:07.596Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d85f8",
          },
          {
            number: "1",
            ref: {
              _id: "620a595fdafc5bd29f9d85fc",
              name: "game of thrones s06e01",
              basename: "game of thrones",
              filename:
                "game.of.thrones.s06e01.the.red.woman.vostfr.720p.TVrip.Xvid.dRuIdE.avi",
              ext: ".avi",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 6",
              type: "tv",
              episode: "1",
              season: "6",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.618Z",
              updatedAt: "2022-02-14T13:30:07.618Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d860a",
          },
          {
            number: "4",
            ref: {
              _id: "620a595fdafc5bd29f9d860d",
              name: "game of thrones s06e04",
              basename: "game of thrones",
              filename:
                "game.of.thrones.s06e04.book.of.the.stranger.vostfr.720p.TVrip.Xvid.dRuIdE.avi",
              ext: ".avi",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 6",
              type: "tv",
              episode: "4",
              season: "6",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.631Z",
              updatedAt: "2022-02-14T13:30:07.631Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d861c",
          },
          {
            number: "2",
            ref: {
              _id: "620a595fdafc5bd29f9d861f",
              name: "game of thrones s06e02",
              basename: "game of thrones",
              filename:
                "game.of.thrones.s06e02.home.vostfr.720p.TVrip.Xvid.dRuIdE.avi",
              ext: ".avi",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 6",
              type: "tv",
              episode: "2",
              season: "6",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.646Z",
              updatedAt: "2022-02-14T13:30:07.646Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d862f",
          },
          {
            number: "3",
            ref: {
              _id: "620a595fdafc5bd29f9d8632",
              name: "game of thrones s06e03",
              basename: "game of thrones",
              filename:
                "game.of.thrones.s06e03.oathbreaker.vostfr.720p.TVrip.Xvid.dRuIdE.avi",
              ext: ".avi",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 6",
              type: "tv",
              episode: "3",
              season: "6",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.661Z",
              updatedAt: "2022-02-14T13:30:07.661Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d8643",
          },
          {
            number: "6",
            ref: {
              _id: "620a595fdafc5bd29f9d8646",
              name: "game of thrones s06e06",
              basename: "game of thrones",
              filename:
                "game.of.thrones.s06e06.blood.of.my.blood.vostfr.720p.TVrip.Xvid.dRuIdE.avi",
              ext: ".avi",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 6",
              type: "tv",
              episode: "6",
              season: "6",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.677Z",
              updatedAt: "2022-02-14T13:30:07.677Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d8658",
          },
          {
            number: "9",
            ref: {
              _id: "620a595fdafc5bd29f9d865b",
              name: "game of thrones s06e09",
              basename: "game of thrones",
              filename: "Game.of.Thrones.S06E09.SUBFRENCH.HDTV.x264-SVR.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 6",
              type: "tv",
              episode: "9",
              season: "6",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.695Z",
              updatedAt: "2022-02-14T13:30:07.695Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d866e",
          },
          {
            number: "8",
            ref: {
              _id: "620a595fdafc5bd29f9d8671",
              name: "game of thrones s06e08",
              basename: "game of thrones",
              filename: "Game of ThronesS06E08.mp4",
              ext: ".mp4",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 6",
              type: "tv",
              episode: "8",
              season: "6",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.710Z",
              updatedAt: "2022-02-14T13:30:07.710Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d8685",
          },
          {
            number: "5",
            ref: {
              _id: "620a595fdafc5bd29f9d8688",
              name: "game of thrones s06e05",
              basename: "game of thrones",
              filename:
                "game.of.thrones.s06e05.the.door.vostfr.720p.TVrip.Xvid.dRuIdE.avi",
              ext: ".avi",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 6",
              type: "tv",
              episode: "5",
              season: "6",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.725Z",
              updatedAt: "2022-02-14T13:30:07.725Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d869d",
          },
        ],
        _id: "620a595fdafc5bd29f9d85e7",
      },
      {
        number: "3",
        episodes: [
          {
            number: "10",
            ref: {
              _id: "620a595fdafc5bd29f9d86a0",
              name: "game of thrones s03e10",
              basename: "game of thrones",
              filename: "Game.of.Thrones.S03E10.720p.HDTV.x264-EVOLVE.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game.Of.Thrones.S03.Season.3.COMPLETE.720p.HDTV.x264-PublicHD",
              type: "tv",
              episode: "10",
              season: "3",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.737Z",
              updatedAt: "2022-02-14T13:30:07.737Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d86b7",
          },
          {
            number: "8",
            ref: {
              _id: "620a595fdafc5bd29f9d86ba",
              name: "game of thrones s03e08",
              basename: "game of thrones",
              filename: "Game.of.Thrones.S03E08.720p.HDTV.x264-EVOLVE.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game.Of.Thrones.S03.Season.3.COMPLETE.720p.HDTV.x264-PublicHD",
              type: "tv",
              episode: "8",
              season: "3",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.751Z",
              updatedAt: "2022-02-14T13:30:07.751Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d86d2",
          },
          {
            number: "9",
            ref: {
              _id: "620a595fdafc5bd29f9d86d5",
              name: "game of thrones s03e09",
              basename: "game of thrones",
              filename: "Game.of.Thrones.S03E09.720p.HDTV.x264-EVOLVE.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game.Of.Thrones.S03.Season.3.COMPLETE.720p.HDTV.x264-PublicHD",
              type: "tv",
              episode: "9",
              season: "3",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.765Z",
              updatedAt: "2022-02-14T13:30:07.765Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d86ee",
          },
          {
            number: "5",
            ref: {
              _id: "620a595fdafc5bd29f9d86f1",
              name: "game of thrones s03e05",
              basename: "game of thrones",
              filename:
                "Game.Of.Thrones.S03E05.PROPER.720p.HDTV.x264-KILLERS.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game.Of.Thrones.S03.Season.3.COMPLETE.720p.HDTV.x264-PublicHD",
              type: "tv",
              episode: "5",
              season: "3",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.778Z",
              updatedAt: "2022-02-14T13:30:07.778Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d870b",
          },
          {
            number: "6",
            ref: {
              _id: "620a595fdafc5bd29f9d870e",
              name: "game of thrones s03e06",
              basename: "game of thrones",
              filename:
                "Game.of.Thrones.S03E06.INTERNAL.720p.HDTV.x264-EVOLVE.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game.Of.Thrones.S03.Season.3.COMPLETE.720p.HDTV.x264-PublicHD",
              type: "tv",
              episode: "6",
              season: "3",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.794Z",
              updatedAt: "2022-02-14T13:30:07.794Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d8729",
          },
          {
            number: "3",
            ref: {
              _id: "620a595fdafc5bd29f9d872c",
              name: "game of thrones s03e03",
              basename: "game of thrones",
              filename: "Game.of.Thrones.S03E03.720p.HDTV.x264-EVOLVE.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game.Of.Thrones.S03.Season.3.COMPLETE.720p.HDTV.x264-PublicHD",
              type: "tv",
              episode: "3",
              season: "3",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.810Z",
              updatedAt: "2022-02-14T13:30:07.810Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d8748",
          },
          {
            number: "7",
            ref: {
              _id: "620a595fdafc5bd29f9d874b",
              name: "game of thrones s03e07",
              basename: "game of thrones",
              filename: "Game.of.Thrones.S03E07.720p.HDTV.x264-EVOLVE.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game.Of.Thrones.S03.Season.3.COMPLETE.720p.HDTV.x264-PublicHD",
              type: "tv",
              episode: "7",
              season: "3",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.826Z",
              updatedAt: "2022-02-14T13:30:07.826Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d8768",
          },
          {
            number: "1",
            ref: {
              _id: "620a595fdafc5bd29f9d876b",
              name: "game of thrones s03e01",
              basename: "game of thrones",
              filename:
                "Game.of.Thrones.S03E01.REPACK.720p.HDTV.x264-EVOLVE.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game.Of.Thrones.S03.Season.3.COMPLETE.720p.HDTV.x264-PublicHD",
              type: "tv",
              episode: "1",
              season: "3",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.844Z",
              updatedAt: "2022-02-14T13:30:07.844Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d8789",
          },
          {
            number: "2",
            ref: {
              _id: "620a595fdafc5bd29f9d878c",
              name: "game of thrones s03e02",
              basename: "game of thrones",
              filename: "Game.of.Thrones.S03E02.720p.HDTV.x264-IMMERSE.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game.Of.Thrones.S03.Season.3.COMPLETE.720p.HDTV.x264-PublicHD",
              type: "tv",
              episode: "2",
              season: "3",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.857Z",
              updatedAt: "2022-02-14T13:30:07.857Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d87ab",
          },
          {
            number: "4",
            ref: {
              _id: "620a595fdafc5bd29f9d87ae",
              name: "game of thrones s03e04",
              basename: "game of thrones",
              filename: "Game.of.Thrones.S03E04.720p.HDTV.x264-EVOLVE.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game.Of.Thrones.S03.Season.3.COMPLETE.720p.HDTV.x264-PublicHD",
              type: "tv",
              episode: "4",
              season: "3",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.875Z",
              updatedAt: "2022-02-14T13:30:07.875Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d87ce",
          },
        ],
        _id: "620a595fdafc5bd29f9d86b6",
      },
      {
        number: "8",
        episodes: [
          {
            number: "4",
            ref: {
              _id: "620a595fdafc5bd29f9d87d1",
              name: "game of thrones s08e04",
              basename: "game of thrones",
              filename:
                "Game.of.Thrones.S08E04.The.Last.of.the.Starks.720p.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game Of Thrones S08 Complete Season 8 720p x264 AC3 5.1 [MKV]",
              type: "tv",
              episode: "4",
              season: "8",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.893Z",
              updatedAt: "2022-02-14T13:30:07.893Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d87f3",
          },
          {
            number: "1",
            ref: {
              _id: "620a595fdafc5bd29f9d87f6",
              name: "game of thrones s08e01",
              basename: "game of thrones",
              filename: "Game.of.Thrones.S08E01.Winterfell.720p.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game Of Thrones S08 Complete Season 8 720p x264 AC3 5.1 [MKV]",
              type: "tv",
              episode: "1",
              season: "8",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.906Z",
              updatedAt: "2022-02-14T13:30:07.906Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d8819",
          },
          {
            number: "3",
            ref: {
              _id: "620a595fdafc5bd29f9d881c",
              name: "game of thrones s08e03",
              basename: "game of thrones",
              filename: "Game.of.Thrones.S08E03.The.Long.Night.720p.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game Of Thrones S08 Complete Season 8 720p x264 AC3 5.1 [MKV]",
              type: "tv",
              episode: "3",
              season: "8",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.919Z",
              updatedAt: "2022-02-14T13:30:07.919Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d8840",
          },
          {
            number: "2",
            ref: {
              _id: "620a595fdafc5bd29f9d8843",
              name: "game of thrones s08e02",
              basename: "game of thrones",
              filename:
                "Game.of.Thrones.S08E02.A.Knight.of.the.Seven.Kingdoms.720p.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game Of Thrones S08 Complete Season 8 720p x264 AC3 5.1 [MKV]",
              type: "tv",
              episode: "2",
              season: "8",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.934Z",
              updatedAt: "2022-02-14T13:30:07.934Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d8868",
          },
          {
            number: "5",
            ref: {
              _id: "620a595fdafc5bd29f9d886b",
              name: "game of thrones s08e05",
              basename: "game of thrones",
              filename: "Game.of.Thrones.S08E05.The.Bells.720p.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game Of Thrones S08 Complete Season 8 720p x264 AC3 5.1 [MKV]",
              type: "tv",
              episode: "5",
              season: "8",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.947Z",
              updatedAt: "2022-02-14T13:30:07.947Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d8891",
          },
          {
            number: "6",
            ref: {
              _id: "620a595fdafc5bd29f9d8894",
              name: "game of thrones s08e06",
              basename: "game of thrones",
              filename: "Game.of.Thrones.S08E06.The.Iron.Throne.720p.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game Of Thrones S08 Complete Season 8 720p x264 AC3 5.1 [MKV]",
              type: "tv",
              episode: "6",
              season: "8",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.962Z",
              updatedAt: "2022-02-14T13:30:07.962Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d88bb",
          },
        ],
        _id: "620a595fdafc5bd29f9d87f2",
      },
      {
        number: "4",
        episodes: [
          {
            number: "4",
            ref: {
              _id: "620a595fdafc5bd29f9d88be",
              name: "game of thrones s04e04",
              basename: "game of thrones",
              filename:
                "Game.Of.Thrones.S04E04.PROPER.VOSTFR.HDTV.XVID-Ateam.avi",
              ext: ".avi",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 4",
              type: "tv",
              episode: "4",
              season: "4",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.976Z",
              updatedAt: "2022-02-14T13:30:07.976Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d88e7",
          },
          {
            number: "3",
            ref: {
              _id: "620a595fdafc5bd29f9d88ea",
              name: "game of thrones s04e03",
              basename: "game of thrones",
              filename:
                "Game.of.Thrones.S04E03.FASTSUB.VOSTFR.HDTV.x264-SP3CTR3.mp4",
              ext: ".mp4",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 4/Game.of.Thrones.S04E03.FASTSUB.VOSTFR.HDTV.x264-SP3CTR3",
              type: "tv",
              episode: "3",
              season: "4",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:07.989Z",
              updatedAt: "2022-02-14T13:30:07.989Z",
              __v: 0,
            },
            _id: "620a595fdafc5bd29f9d8914",
          },
          {
            number: "5",
            ref: {
              _id: "620a5960dafc5bd29f9d8917",
              name: "game of thrones s04e05",
              basename: "game of thrones",
              filename:
                "Game.of.Thrones.S04E05.FASTSUB.VOSTFR.720p.HDTV.x264-ADDiCTiON.mp4",
              ext: ".mp4",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 4/Game.of.Thrones.S04E05.FASTSUB.VOSTFR.HDTV.x264-ADDiCTiON",
              type: "tv",
              episode: "5",
              season: "4",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.019Z",
              updatedAt: "2022-02-14T13:30:08.019Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d8942",
          },
          {
            number: "9",
            ref: {
              _id: "620a5960dafc5bd29f9d8945",
              name: "game of thrones s04e09",
              basename: "game of thrones",
              filename:
                "Game.Of.Thrones.S04E09.PROPER.VOSTFR.HDTV.x264-ATeam.mp4",
              ext: ".mp4",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 4",
              type: "tv",
              episode: "9",
              season: "4",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.030Z",
              updatedAt: "2022-02-14T13:30:08.030Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d8971",
          },
          {
            number: "1",
            ref: {
              _id: "620a5960dafc5bd29f9d8974",
              name: "game of thrones s04e01",
              basename: "game of thrones",
              filename:
                "Game.of.Thrones.S04E01.FASTSUB.VOSTFR.HDTV.XviD-ADDiCTiON.avi",
              ext: ".avi",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 4/Game.of.Thrones.S04E01.FASTSUB.VOSTFR.HDTV.XviD-ADDiCTiON",
              type: "tv",
              episode: "1",
              season: "4",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.042Z",
              updatedAt: "2022-02-14T13:30:08.042Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d89a1",
          },
          {
            number: "7",
            ref: {
              _id: "620a5960dafc5bd29f9d89a4",
              name: "game of thrones s04e07",
              basename: "game of thrones",
              filename:
                "Game.of.Thrones.S04E07.FASTSUB.VOSTFR.HDTV.x264-ADDiCTiON.mp4",
              ext: ".mp4",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 4",
              type: "tv",
              episode: "7",
              season: "4",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.056Z",
              updatedAt: "2022-02-14T13:30:08.056Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d89d2",
          },
          {
            number: "8",
            ref: {
              _id: "620a5960dafc5bd29f9d89d5",
              name: "game of thrones s04e08",
              basename: "game of thrones",
              filename:
                "Game.of.Thrones.S04E08.FASTSUB.VOSTFR.HDTV.XviD-ADDiCTiON.avi",
              ext: ".avi",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 4/Game.of.Thrones.S04E08.FASTSUB.VOSTFR.HDTV.XviD-ADDiCTiON",
              type: "tv",
              episode: "8",
              season: "4",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.067Z",
              updatedAt: "2022-02-14T13:30:08.067Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d8a04",
          },
          {
            number: "6",
            ref: {
              _id: "620a5960dafc5bd29f9d8a07",
              name: "game of thrones s04e06",
              basename: "game of thrones",
              filename:
                "Game.of.Thrones.S04E06.PROPER.VOSTFR.HDTV.XviD-ATeam.avi",
              ext: ".avi",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 4/Game.of.Thrones.S04E06.PROPER.VOSTFR.HDTV.XviD-ATeam",
              type: "tv",
              episode: "6",
              season: "4",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.077Z",
              updatedAt: "2022-02-14T13:30:08.077Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d8a37",
          },
          {
            number: "2",
            ref: {
              _id: "620a5960dafc5bd29f9d8a3a",
              name: "game of thrones s04e02",
              basename: "game of thrones",
              filename:
                "Game.of.Thrones.S04E02.FASTSUB.VOSTFR.HDTV.XviD-ADDiCTiON.avi",
              ext: ".avi",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 4/Game.of.Thrones.S04E02.FASTSUB.VOSTFR.HDTV.XviD-ADDiCTiON",
              type: "tv",
              episode: "2",
              season: "4",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.088Z",
              updatedAt: "2022-02-14T13:30:08.088Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d8a6b",
          },
          {
            number: "10",
            ref: {
              _id: "620a5960dafc5bd29f9d8a6e",
              name: "game of thrones s04e10",
              basename: "game of thrones",
              filename:
                "Game.Of.Thrones.S04E10.FiNAL.FASTSUB.VOSTFR.HDTV.X264-ADDiCTiON.mp4",
              ext: ".mp4",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 4",
              type: "tv",
              episode: "10",
              season: "4",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.100Z",
              updatedAt: "2022-02-14T13:30:08.100Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d8aa0",
          },
        ],
        _id: "620a595fdafc5bd29f9d88e6",
      },
      {
        number: "5",
        episodes: [
          {
            number: "7",
            ref: {
              _id: "620a5960dafc5bd29f9d8aa3",
              name: "game of thrones s05e07",
              basename: "game of thrones",
              filename:
                "Game.Of.Thrones.S05E07.FASTSUB.VOSTFR.HDTV.XviD-ADDiCTiON.avi",
              ext: ".avi",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 5/Game.Of.Thrones.S05E07.FASTSUB.VOSTFR.HDTV.XviD-ADDiCTiON",
              type: "tv",
              episode: "7",
              season: "5",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.109Z",
              updatedAt: "2022-02-14T13:30:08.109Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d8ad7",
          },
          {
            number: "10",
            ref: {
              _id: "620a5960dafc5bd29f9d8ada",
              name: "game of thrones s05e10",
              basename: "game of thrones",
              filename:
                "Game.of.Thrones.S05E10.PROPER.VOSTFR.HDTV.XviD-ATeam.avi",
              ext: ".avi",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 5/Game.of.Thrones.S05E10.PROPER.VOSTFR.HDTV.XviD-ATeam",
              type: "tv",
              episode: "10",
              season: "5",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.117Z",
              updatedAt: "2022-02-14T13:30:08.117Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d8b0f",
          },
          {
            number: "3",
            ref: {
              _id: "620a5960dafc5bd29f9d8b12",
              name: "game of thrones s05e03",
              basename: "game of thrones",
              filename:
                "Game.of.Thrones.S05E03.VOSTFR.1080p.HDTVRip.MPEG4-AVC.AC3-NoTeam .mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 5",
              type: "tv",
              episode: "3",
              season: "5",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.125Z",
              updatedAt: "2022-02-14T13:30:08.125Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d8b48",
          },
          {
            number: "6",
            ref: {
              _id: "620a5960dafc5bd29f9d8b4b",
              name: "game of thrones s05e06",
              basename: "game of thrones",
              filename: "Game.Of.Thrones.S05E06.VOSTFR.HDTV.XviD-ATeam.avi",
              ext: ".avi",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 5/Game.Of.Thrones.S05E06.VOSTFR.HDTV.XviD-ATeam",
              type: "tv",
              episode: "6",
              season: "5",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.134Z",
              updatedAt: "2022-02-14T13:30:08.134Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d8b82",
          },
          {
            number: "1",
            ref: {
              _id: "620a5960dafc5bd29f9d8b85",
              name: "game of thrones s05e01",
              basename: "game of thrones",
              filename:
                "Game.of.Thrones.S05E01.VOSTFR.1080p.HDTVRip.MPEG4-AVC.AC3-NoTeam .mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 5",
              type: "tv",
              episode: "1",
              season: "5",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.143Z",
              updatedAt: "2022-02-14T13:30:08.143Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d8bbd",
          },
          {
            number: "0",
            ref: {
              _id: "620a5960dafc5bd29f9d8bc0",
              name: "game of thrones s05e00",
              basename: "game of thrones",
              filename:
                "Game.of.Thrones.S05E00.FASTSUB.VOSTFR.HDTV.XviD-ADDiCTiON.avi",
              ext: ".avi",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 5/Game.of.Thrones.S05E00.FASTSUB.VOSTFR.HDTV.XviD-ADDiCTiON",
              type: "tv",
              episode: "0",
              season: "5",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.153Z",
              updatedAt: "2022-02-14T13:30:08.153Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d8bf9",
          },
          {
            number: "5",
            ref: {
              _id: "620a5960dafc5bd29f9d8bfc",
              name: "game of thrones s05e05",
              basename: "game of thrones",
              filename: "Game.of.Thrones.S05E05.VOSTFR.HDTV.x264-ASAP.mp4",
              ext: ".mp4",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 5",
              type: "tv",
              episode: "5",
              season: "5",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.162Z",
              updatedAt: "2022-02-14T13:30:08.162Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d8c36",
          },
          {
            number: "4",
            ref: {
              _id: "620a5960dafc5bd29f9d8c39",
              name: "game of thrones s05e04",
              basename: "game of thrones",
              filename:
                "Game.of.Thrones.S05E04.FASTSUB.VOSTFR.HDTV.x264-ADDiCTiON.mp4",
              ext: ".mp4",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 5",
              type: "tv",
              episode: "4",
              season: "5",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.173Z",
              updatedAt: "2022-02-14T13:30:08.173Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d8c74",
          },
          {
            number: "8",
            ref: {
              _id: "620a5960dafc5bd29f9d8c77",
              name: "game of thrones s05e08",
              basename: "game of thrones",
              filename:
                "Game.Of.Thrones.S05E08.FASTSUB.VOSTFR.HDTV.XviD-ADDiCTiON.avi",
              ext: ".avi",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 5/Game.Of.Thrones.S05E08.FASTSUB.VOSTFR.HDTV.XviD-ADDiCTiON",
              type: "tv",
              episode: "8",
              season: "5",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.181Z",
              updatedAt: "2022-02-14T13:30:08.181Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d8cb3",
          },
          {
            number: "2",
            ref: {
              _id: "620a5960dafc5bd29f9d8cb6",
              name: "game of thrones s05e02",
              basename: "game of thrones",
              filename:
                "Game.of.Thrones.S05E02.VOSTFR.1080p.HDTVRip.MPEG4-AVC.AC3-NoTeam .mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 5",
              type: "tv",
              episode: "2",
              season: "5",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.191Z",
              updatedAt: "2022-02-14T13:30:08.191Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d8cf3",
          },
          {
            number: "9",
            ref: {
              _id: "620a5960dafc5bd29f9d8cf6",
              name: "game of thrones s05e09",
              basename: "game of thrones",
              filename:
                "Game.Of.Thrones.S05E09.FASTSUB.VOSTFR.HDTV.XviD-ADDiCTiON.avi",
              ext: ".avi",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Saison 5/Game.Of.Thrones.S05E09.FASTSUB.VOSTFR.HDTV.XviD-ADDiCTiON",
              type: "tv",
              episode: "9",
              season: "5",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.202Z",
              updatedAt: "2022-02-14T13:30:08.202Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d8d34",
          },
        ],
        _id: "620a5960dafc5bd29f9d8ad6",
      },
      {
        number: "1",
        episodes: [
          {
            number: "4",
            ref: {
              _id: "620a5960dafc5bd29f9d8d37",
              name: "game of thrones s01e04",
              basename: "game of thrones",
              filename: "S01E04- Cripples, Bastards, and Broken Things.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game of Thrones Season 1 720p BluRay- mRs",
              type: "tv",
              episode: "4",
              season: "1",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.212Z",
              updatedAt: "2022-02-14T13:30:08.212Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d8d77",
          },
          {
            number: "5",
            ref: {
              _id: "620a5960dafc5bd29f9d8d7a",
              name: "game of thrones s01e05",
              basename: "game of thrones",
              filename: "S01E05- The Wolf and the Lion.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game of Thrones Season 1 720p BluRay- mRs",
              type: "tv",
              episode: "5",
              season: "1",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.220Z",
              updatedAt: "2022-02-14T13:30:08.220Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d8dbb",
          },
          {
            number: "9",
            ref: {
              _id: "620a5960dafc5bd29f9d8dbe",
              name: "game of thrones s01e09",
              basename: "game of thrones",
              filename: "S01E09- Baelor.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game of Thrones Season 1 720p BluRay- mRs",
              type: "tv",
              episode: "9",
              season: "1",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.228Z",
              updatedAt: "2022-02-14T13:30:08.228Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d8e00",
          },
          {
            number: "3",
            ref: {
              _id: "620a5960dafc5bd29f9d8e03",
              name: "game of thrones s01e03",
              basename: "game of thrones",
              filename: "S01E03- Lord Snow.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game of Thrones Season 1 720p BluRay- mRs",
              type: "tv",
              episode: "3",
              season: "1",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.237Z",
              updatedAt: "2022-02-14T13:30:08.237Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d8e46",
          },
          {
            number: "7",
            ref: {
              _id: "620a5960dafc5bd29f9d8e49",
              name: "game of thrones s01e07",
              basename: "game of thrones",
              filename: "S01E07- You Win or You Die.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game of Thrones Season 1 720p BluRay- mRs",
              type: "tv",
              episode: "7",
              season: "1",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.247Z",
              updatedAt: "2022-02-14T13:30:08.247Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d8e8d",
          },
          {
            number: "1",
            ref: {
              _id: "620a5960dafc5bd29f9d8e90",
              name: "game of thrones s01e01",
              basename: "game of thrones",
              filename: "S01E01- Winter Is Coming.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game of Thrones Season 1 720p BluRay- mRs",
              type: "tv",
              episode: "1",
              season: "1",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.256Z",
              updatedAt: "2022-02-14T13:30:08.256Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d8ed5",
          },
          {
            number: "6",
            ref: {
              _id: "620a5960dafc5bd29f9d8ed8",
              name: "game of thrones s01e06",
              basename: "game of thrones",
              filename: "S01E06- A Golden Crown.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game of Thrones Season 1 720p BluRay- mRs",
              type: "tv",
              episode: "6",
              season: "1",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.267Z",
              updatedAt: "2022-02-14T13:30:08.267Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d8f1e",
          },
          {
            number: "2",
            ref: {
              _id: "620a5960dafc5bd29f9d8f21",
              name: "game of thrones s01e02",
              basename: "game of thrones",
              filename: "S01E02- The Kingsroad.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game of Thrones Season 1 720p BluRay- mRs",
              type: "tv",
              episode: "2",
              season: "1",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.281Z",
              updatedAt: "2022-02-14T13:30:08.281Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d8f68",
          },
          {
            number: "10",
            ref: {
              _id: "620a5960dafc5bd29f9d8f6b",
              name: "game of thrones s01e10",
              basename: "game of thrones",
              filename: "S01E10- Fire and Blood.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game of Thrones Season 1 720p BluRay- mRs",
              type: "tv",
              episode: "10",
              season: "1",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.291Z",
              updatedAt: "2022-02-14T13:30:08.291Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d8fb3",
          },
          {
            number: "8",
            ref: {
              _id: "620a5960dafc5bd29f9d8fb6",
              name: "game of thrones s01e08",
              basename: "game of thrones",
              filename: "S01E08- The Pointy End.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game of Thrones Season 1 720p BluRay- mRs",
              type: "tv",
              episode: "8",
              season: "1",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.301Z",
              updatedAt: "2022-02-14T13:30:08.301Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d8fff",
          },
        ],
        _id: "620a5960dafc5bd29f9d8d76",
      },
      {
        number: "2",
        episodes: [
          {
            number: "8",
            ref: {
              _id: "620a5960dafc5bd29f9d9002",
              name: "game of thrones s02e08",
              basename: "game of thrones",
              filename:
                "Game.of.Thrones.S02E08.720p.BluRay.450MB.ShAaNiG.com.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game.of.Thrones.S02.720p.BluRay.x264.ShAaNiG",
              type: "tv",
              episode: "8",
              season: "2",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.313Z",
              updatedAt: "2022-02-14T13:30:08.313Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d904d",
          },
          {
            number: "4",
            ref: {
              _id: "620a5960dafc5bd29f9d9050",
              name: "game of thrones s02e04",
              basename: "game of thrones",
              filename:
                "Game.of.Thrones.S02E04.720p.BluRay.450MB.ShAaNiG.com.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game.of.Thrones.S02.720p.BluRay.x264.ShAaNiG",
              type: "tv",
              episode: "4",
              season: "2",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.323Z",
              updatedAt: "2022-02-14T13:30:08.323Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d909c",
          },
          {
            number: "6",
            ref: {
              _id: "620a5960dafc5bd29f9d909f",
              name: "game of thrones s02e06",
              basename: "game of thrones",
              filename:
                "Game.of.Thrones.S02E06.720p.BluRay.450MB.ShAaNiG.com.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game.of.Thrones.S02.720p.BluRay.x264.ShAaNiG",
              type: "tv",
              episode: "6",
              season: "2",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.333Z",
              updatedAt: "2022-02-14T13:30:08.333Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d90ec",
          },
          {
            number: "10",
            ref: {
              _id: "620a5960dafc5bd29f9d90ef",
              name: "game of thrones s02e10",
              basename: "game of thrones",
              filename:
                "Game.of.Thrones.S02E10.720p.BluRay.500MB.ShAaNiG.com.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game.of.Thrones.S02.720p.BluRay.x264.ShAaNiG",
              type: "tv",
              episode: "10",
              season: "2",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.345Z",
              updatedAt: "2022-02-14T13:30:08.345Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d913d",
          },
          {
            number: "2",
            ref: {
              _id: "620a5960dafc5bd29f9d9140",
              name: "game of thrones s02e02",
              basename: "game of thrones",
              filename:
                "Game.of.Thrones.S02E02.720p.BluRay.450MB.ShAaNiG.com.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game.of.Thrones.S02.720p.BluRay.x264.ShAaNiG",
              type: "tv",
              episode: "2",
              season: "2",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.359Z",
              updatedAt: "2022-02-14T13:30:08.359Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d918f",
          },
          {
            number: "1",
            ref: {
              _id: "620a5960dafc5bd29f9d9192",
              name: "game of thrones s02e01",
              basename: "game of thrones",
              filename:
                "Game.of.Thrones.S02E01.720p.BluRay.450MB.ShAaNiG.com.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game.of.Thrones.S02.720p.BluRay.x264.ShAaNiG",
              type: "tv",
              episode: "1",
              season: "2",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.370Z",
              updatedAt: "2022-02-14T13:30:08.370Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d91e2",
          },
          {
            number: "7",
            ref: {
              _id: "620a5960dafc5bd29f9d91e5",
              name: "game of thrones s02e07",
              basename: "game of thrones",
              filename:
                "Game.of.Thrones.S02E07.720p.BluRay.450MB.ShAaNiG.com.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game.of.Thrones.S02.720p.BluRay.x264.ShAaNiG",
              type: "tv",
              episode: "7",
              season: "2",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.380Z",
              updatedAt: "2022-02-14T13:30:08.380Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d9236",
          },
          {
            number: "5",
            ref: {
              _id: "620a5960dafc5bd29f9d9239",
              name: "game of thrones s02e05",
              basename: "game of thrones",
              filename:
                "Game.of.Thrones.S02E05.720p.BluRay.450MB.ShAaNiG.com.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game.of.Thrones.S02.720p.BluRay.x264.ShAaNiG",
              type: "tv",
              episode: "5",
              season: "2",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.393Z",
              updatedAt: "2022-02-14T13:30:08.393Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d928b",
          },
          {
            number: "3",
            ref: {
              _id: "620a5960dafc5bd29f9d928e",
              name: "game of thrones s02e03",
              basename: "game of thrones",
              filename:
                "Game.of.Thrones.S02E03.720p.BluRay.450MB.ShAaNiG.com.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game.of.Thrones.S02.720p.BluRay.x264.ShAaNiG",
              type: "tv",
              episode: "3",
              season: "2",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.407Z",
              updatedAt: "2022-02-14T13:30:08.407Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d92e1",
          },
          {
            number: "9",
            ref: {
              _id: "620a5960dafc5bd29f9d92e4",
              name: "game of thrones s02e09",
              basename: "game of thrones",
              filename:
                "Game.of.Thrones.S02E09.720p.BluRay.450MB.ShAaNiG.com.mkv",
              ext: ".mkv",
              location:
                "/Users/pielov/workspace/quickFlix/backend/public/videos/Game Of Thrones/Game.of.Thrones.S02.720p.BluRay.x264.ShAaNiG",
              type: "tv",
              episode: "9",
              season: "2",
              genres: [],
              subtitles: [],
              trailerYtCode: [],
              posterPath: [],
              createdAt: "2022-02-14T13:30:08.420Z",
              updatedAt: "2022-02-14T13:30:08.420Z",
              __v: 0,
            },
            _id: "620a5960dafc5bd29f9d9338",
          },
        ],
        _id: "620a5960dafc5bd29f9d904c",
      },
    ],
    originCountry: ["US"],
    posterPath: [
      "u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg",
      "u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg",
    ],
    genres: ["Sci-Fi & Fantasy", "Drama", "Action & Adventure"],
    trailerYtCode: ["bjqEWgDVPe0", "BpJYNVhGf1s"],
    createdAt: "2022-02-14T13:30:07.461Z",
    updatedAt: "2022-02-14T13:48:09.951Z",
    __v: 75,
    firstAirDate: "2011-04-17T00:00:00.000Z",
    idMovieDb: "1399",
    numberEpisode: 73,
    numberSeason: 8,
    resume:
      "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
    score: 8.4,
  };
  const mockDataVideo: Video = {
    _id: "620a5960dafc5bd29f9d9340",
    name: "black widow",
    basename: "black widow",
    filename:
      "[ OxTorrent.nz ]  Black.Widow.2021.FRENCH.BDRip.XviD-EXTREME.avi",
    ext: ".avi",
    location: "/Users/pielov/workspace/quickFlix/backend/public/videos",
    type: "movie",
    episode: "",
    season: "",
    year: "2021-01-01T00:00:00.000Z",
    genres: ["Action", "Adventure", "Science Fiction"],
    subtitles: [],
    trailerYtCode: [
      "6SGUlutHc1w",
      "UO3qJZrZoLE",
      "pBVPlyM2T3Q",
      "2Fcn1_Uew5A",
      "sprChQ9_9kQ",
    ],
    posterPath: [
      "qAZ0pzat24kLdO3o8ejmbLxyOac.jpg",
      "qAZ0pzat24kLdO3o8ejmbLxyOac.jpg",
    ],
    createdAt: "2022-02-14T13:30:08.433Z",
    updatedAt: "2022-02-14T13:47:34.860Z",
    __v: 2,
    idMovieDb: "497698",
    releaseDate: "2021-07-07T00:00:00.000Z",
    resume:
      "Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.",
    score: 7.5,
  };

  return (
    <div className="w-screen h-screen grid place-items-center bg-gray-300">
      <Card
        key={nanoid()}
        name={mockDataVideo.name}
        id={mockDataVideo._id}
        posterPath={mockDataVideo.posterPath ? mockDataVideo.posterPath[0] : ""}
        ytKey={mockDataVideo.trailerYtCode}
        genres={mockDataVideo.genres}
      />
    </div>
  );
}
